<?php

use Illuminate\Database\Seeder;
use App\Country;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::truncate();
        $countries = array(
            array('name'   => 'Afganistán',
                  'name_1' => 'Afghanistan',
                  'name_2' => 'Afeganistão',
                  'code'   => 'AF',
                  'flag'   => 'Afghanistan.png'
            ),
            array('name'   => 'Albania',
                  'name_1' => 'Albania',
                  'name_2' => 'Albânia',
                  'code'   => 'AL',
                  'flag'   => 'Albania.png'
            ),
            array('name'   => 'Alemania',
                  'name_1' => 'Germany',
                  'name_2' => 'Alemanha',
                  'code'   => 'DE',
                  'flag'   => 'Germany.png'
            ),
            array('name'   => 'Andorra',
                  'name_1' => 'Andorra',
                  'name_2' => 'Andorra',
                  'code'   => 'AD',
                  'flag'   => 'Andorra.png'
            ),
            array('name'   => 'Angola',
                  'name_1' => 'Angola',
                  'name_2' => 'Angola',
                  'code'   => 'AO',
                  'flag'   => 'Angola.png'
            ),
            array('name'   => 'Anguila',
                  'name_1' => 'Anguilla',
                  'name_2' => 'Anguilla',
                  'code'   => 'AI',
                  'flag'   => 'Anguilla.png'
            ),
            array('name'   => 'Antártida',
                  'name_1' => 'Antarctica',
                  'name_2' => 'Antártida',
                  'code'   => 'AQ',
                  'flag'   => 'Antarctica.png'
            ),
            array('name'   => 'Antigua y Barbuda',
                  'name_1' => 'Antigua & Barbuda',
                  'name_2' => 'Antígua e Barbuda',
                  'code'   => 'AG',
                  'flag'   => 'Antigua & Barbuda.png'
            ),
            array('name'   => 'Arabia Saudí',
                  'name_1' => 'Saudi Arabia',
                  'name_2' => 'Arábia Saudita',
                  'code'   => 'SA',
                  'flag'   => 'Saudi Arabia.png'
            ),
            array('name'   => 'Argelia',
                  'name_1' => 'Algeria',
                  'name_2' => 'Argélia',
                  'code'   => 'DZ',
                  'flag'   => 'Algeria.png'
            ),
            array('name'   => 'Argentina',
                  'name_1' => 'Argentina',
                  'name_2' => 'Argentina',
                  'code'   => 'AR',
                  'flag'   => 'Argentina.png'
            ),
            array('name'   => 'Armenia',
                  'name_1' => 'Armenia',
                  'name_2' => 'Armênia',
                  'code'   => 'AM',
                  'flag'   => 'Armenia.png'
            ),
            array('name' => 'Aruba', 'name_1' => 'Aruba', 'name_2' => 'Aruba', 'code' => 'AW', 'flag' => 'Aruba.png'),
            array('name'   => 'Australia',
                  'name_1' => 'Australia',
                  'name_2' => 'Austrália',
                  'code'   => 'AU',
                  'flag'   => 'Australia.png'
            ),
            array('name'   => 'Austria',
                  'name_1' => 'Austria',
                  'name_2' => 'Áustria',
                  'code'   => 'AT',
                  'flag'   => 'Austria.png'
            ),
            array('name'   => 'Azerbaiyán',
                  'name_1' => 'Azerbaijan',
                  'name_2' => 'Azerbaijão',
                  'code'   => 'AZ',
                  'flag'   => 'Azerbaijan.png'
            ),
            array('name'   => 'Bahamas',
                  'name_1' => 'Bahamas',
                  'name_2' => 'Bahamas',
                  'code'   => 'BS',
                  'flag'   => 'Bahamas.png'
            ),
            array('name'   => 'Bangladés',
                  'name_1' => 'Bangladesh',
                  'name_2' => 'Bangladesh',
                  'code'   => 'BD',
                  'flag'   => 'Bangladesh.png'
            ),
            array('name'   => 'Barbados',
                  'name_1' => 'Barbados',
                  'name_2' => 'Barbados',
                  'code'   => 'BB',
                  'flag'   => 'Barbados.png'
            ),
            array('name'   => 'Baréin',
                  'name_1' => 'Bahrain',
                  'name_2' => 'Bahrein',
                  'code'   => 'BH',
                  'flag'   => 'Bahrain.png'
            ),
            array('name'   => 'Bélgica',
                  'name_1' => 'Belgium',
                  'name_2' => 'Bélgica',
                  'code'   => 'BE',
                  'flag'   => 'Belgium.png'
            ),
            array('name'   => 'Belice',
                  'name_1' => 'Belize',
                  'name_2' => 'Belize',
                  'code'   => 'BZ',
                  'flag'   => 'Belize.png'
            ),
            array('name' => 'Benín', 'name_1' => 'Benin', 'name_2' => 'Benin', 'code' => 'BJ', 'flag' => 'Benin.png'),
            array('name' => 'Bermudas', 'name_1' => 'Bermuda', 'name_2' => 'Bermudas', 'code' => 'BM', 'flag' => null),
            array('name'   => 'Bielorrusia',
                  'name_1' => 'Belarus',
                  'name_2' => 'Bielorrússia',
                  'code'   => 'BY',
                  'flag'   => 'Belarus.png'
            ),
            array('name'   => 'Bolivia',
                  'name_1' => 'Bolivia',
                  'name_2' => 'Bolívia',
                  'code'   => 'BO',
                  'flag'   => 'Bolivia.png'
            ),
            array('name'   => 'Bosnia-Herzegovina',
                  'name_1' => 'Bosnia & Herzegovina',
                  'name_2' => 'Bósnia e Herzegovina',
                  'code'   => 'BA',
                  'flag'   => 'Bosnia & Herzegovina.png'
            ),
            array('name'   => 'Botsuana',
                  'name_1' => 'Botswana',
                  'name_2' => 'Botsuana',
                  'code'   => 'BW',
                  'flag'   => 'Botswana.png'
            ),
            array('name'   => 'Brasil',
                  'name_1' => 'Brazil',
                  'name_2' => 'Brasil',
                  'code'   => 'BR',
                  'flag'   => 'Brazil.png'
            ),
            array('name'   => 'Brunéi',
                  'name_1' => 'Brunei',
                  'name_2' => 'Brunei',
                  'code'   => 'BN',
                  'flag'   => 'Brunei.png'
            ),
            array('name'   => 'Bulgaria',
                  'name_1' => 'Bulgaria',
                  'name_2' => 'Bulgária',
                  'code'   => 'BG',
                  'flag'   => 'Bulgaria.png'
            ),
            array('name'   => 'Burkina Faso',
                  'name_1' => 'Burkina Faso',
                  'name_2' => 'Burquina Faso',
                  'code'   => 'BF',
                  'flag'   => 'Burkina Faso.png'
            ),
            array('name'   => 'Burundi',
                  'name_1' => 'Burundi',
                  'name_2' => 'Burundi',
                  'code'   => 'BI',
                  'flag'   => 'Burundi.png'
            ),
            array('name' => 'Bután', 'name_1' => 'Bhutan', 'name_2' => 'Butão', 'code' => 'BT', 'flag' => 'Bhutan.png'),
            array('name'   => 'Cabo Verde',
                  'name_1' => 'Cape Verde',
                  'name_2' => 'Cabo Verde',
                  'code'   => 'CV',
                  'flag'   => 'Cape Verde.png'
            ),
            array('name'   => 'Camboya',
                  'name_1' => 'Cambodia',
                  'name_2' => 'Camboja',
                  'code'   => 'KH',
                  'flag'   => 'Cambodja.png'
            ),
            array('name'   => 'Camerún',
                  'name_1' => 'Cameroon',
                  'name_2' => 'República dos Camarões',
                  'code'   => 'CM',
                  'flag'   => 'Cameroon.png'
            ),
            array('name'   => 'Canadá',
                  'name_1' => 'Canada',
                  'name_2' => 'Canadá',
                  'code'   => 'CA',
                  'flag'   => 'Canada.png'
            ),
            array('name'   => 'Caribe neerlandés',
                  'name_1' => 'Caribbean Netherlands',
                  'name_2' => 'Países Baixos Caribenhos',
                  'code'   => 'BQ',
                  'flag'   => null
            ),
            array('name' => 'Catar', 'name_1' => 'Qatar', 'name_2' => 'Catar', 'code' => 'QA', 'flag' => 'Qatar.png'),
            array('name'   => 'Ceuta y Melilla',
                  'name_1' => 'Ceuta & Melilla',
                  'name_2' => 'Ceuta e Melilha',
                  'code'   => 'EA',
                  'flag'   => null
            ),
            array('name' => 'Chad', 'name_1' => 'Chad', 'name_2' => 'Chade', 'code' => 'TD', 'flag' => 'Chad.png'),
            array('name' => 'Chile', 'name_1' => 'Chile', 'name_2' => 'Chile', 'code' => 'CL', 'flag' => 'Chile.png'),
            array('name' => 'China', 'name_1' => 'China', 'name_2' => 'China', 'code' => 'CN', 'flag' => 'China.png'),
            array('name'   => 'Chipre',
                  'name_1' => 'Cyprus',
                  'name_2' => 'Chipre',
                  'code'   => 'CY',
                  'flag'   => 'Cyprus.png'
            ),
            array('name'   => 'Ciudad del Vaticano',
                  'name_1' => 'Vatican City',
                  'name_2' => 'Cidade do Vaticano',
                  'code'   => 'VA',
                  'flag'   => 'Vatican City.png'
            ),
            array('name'   => 'Colombia',
                  'name_1' => 'Colombia',
                  'name_2' => 'Colômbia',
                  'code'   => 'CO',
                  'flag'   => 'Colombia.png'
            ),
            array('name'   => 'Comoras',
                  'name_1' => 'Comoros',
                  'name_2' => 'Comores',
                  'code'   => 'KM',
                  'flag'   => 'Comoros.png'
            ),
            array('name'   => 'Corea del Norte',
                  'name_1' => 'North Korea',
                  'name_2' => 'Coreia do Norte',
                  'code'   => 'KP',
                  'flag'   => 'North Korea.png'
            ),
            array('name'   => 'Corea del Sur',
                  'name_1' => 'South Korea',
                  'name_2' => 'Coreia do Sul',
                  'code'   => 'KR',
                  'flag'   => 'South Korea.png'
            ),
            array('name'   => 'Costa de Marfil',
                  'name_1' => 'Côte d’Ivoire',
                  'name_2' => 'Costa do Marfim',
                  'code'   => 'CI',
                  'flag'   => null
            ),
            array('name'   => 'Costa Rica',
                  'name_1' => 'Costa Rica',
                  'name_2' => 'Costa Rica',
                  'code'   => 'CR',
                  'flag'   => 'Costa Rica.png'
            ),
            array('name'   => 'Croacia',
                  'name_1' => 'Croatia',
                  'name_2' => 'Croácia',
                  'code'   => 'HR',
                  'flag'   => 'Croatia.png'
            ),
            array('name' => 'Cuba', 'name_1' => 'Cuba', 'name_2' => 'Cuba', 'code' => 'CU', 'flag' => 'Cuba.png'),
            array('name' => 'Curazao', 'name_1' => 'Curaçao', 'name_2' => 'Curaçao', 'code' => 'CW', 'flag' => null),
            array('name'   => 'Diego García',
                  'name_1' => 'Diego Garcia',
                  'name_2' => 'Diego Garcia',
                  'code'   => 'DG',
                  'flag'   => null
            ),
            array('name'   => 'Dinamarca',
                  'name_1' => 'Denmark',
                  'name_2' => 'Dinamarca',
                  'code'   => 'DK',
                  'flag'   => 'Denmark.png'
            ),
            array('name'   => 'Dominica',
                  'name_1' => 'Dominica',
                  'name_2' => 'Dominica',
                  'code'   => 'DM',
                  'flag'   => 'Dominica.png'
            ),
            array('name'   => 'Ecuador',
                  'name_1' => 'Ecuador',
                  'name_2' => 'Equador',
                  'code'   => 'EC',
                  'flag'   => 'Ecuador.png'
            ),
            array('name' => 'Egipto', 'name_1' => 'Egypt', 'name_2' => 'Egito', 'code' => 'EG', 'flag' => 'Egypt.png'),
            array('name'   => 'El Salvador',
                  'name_1' => 'El Salvador',
                  'name_2' => 'El Salvador',
                  'code'   => 'SV',
                  'flag'   => 'El Salvador.png'
            ),
            array('name'   => 'Emiratos Árabes Unidos',
                  'name_1' => 'United Arab Emirates',
                  'name_2' => 'Emirados Árabes Unidos',
                  'code'   => 'AE',
                  'flag'   => 'United Arab Emirates.png'
            ),
            array('name'   => 'Eritrea',
                  'name_1' => 'Eritrea',
                  'name_2' => 'Eritreia',
                  'code'   => 'ER',
                  'flag'   => 'Eritrea.png'
            ),
            array('name'   => 'Eslovaquia',
                  'name_1' => 'Slovakia',
                  'name_2' => 'Eslováquia',
                  'code'   => 'SK',
                  'flag'   => 'Slovakia.png'
            ),
            array('name'   => 'Eslovenia',
                  'name_1' => 'Slovenia',
                  'name_2' => 'Eslovênia',
                  'code'   => 'SI',
                  'flag'   => 'Slovenia.png'
            ),
            array('name'   => 'España',
                  'name_1' => 'Spain',
                  'name_2' => 'Espanha',
                  'code'   => 'ES',
                  'flag'   => 'Spain.png'
            ),
            array('name'   => 'Estados Unidos',
                  'name_1' => 'United States',
                  'name_2' => 'Estados Unidos',
                  'code'   => 'US',
                  'flag'   => 'United States of America(USA).png'
            ),
            array('name'   => 'Estonia',
                  'name_1' => 'Estonia',
                  'name_2' => 'Estônia',
                  'code'   => 'EE',
                  'flag'   => 'Estonia.png'
            ),
            array('name'   => 'Etiopía',
                  'name_1' => 'Ethiopia',
                  'name_2' => 'Etiópia',
                  'code'   => 'ET',
                  'flag'   => 'Ethiopia.png'
            ),
            array('name'   => 'Filipinas',
                  'name_1' => 'Philippines',
                  'name_2' => 'Filipinas',
                  'code'   => 'PH',
                  'flag'   => 'Philippines.png'
            ),
            array('name'   => 'Finlandia',
                  'name_1' => 'Finland',
                  'name_2' => 'Finlândia',
                  'code'   => 'FI',
                  'flag'   => 'Finland.png'
            ),
            array('name' => 'Fiyi', 'name_1' => 'Fiji', 'name_2' => 'Fiji', 'code' => 'FJ', 'flag' => 'Fiji.png'),
            array('name'   => 'Francia',
                  'name_1' => 'France',
                  'name_2' => 'França',
                  'code'   => 'FR',
                  'flag'   => 'France.png'
            ),
            array('name' => 'Gabón', 'name_1' => 'Gabon', 'name_2' => 'Gabão', 'code' => 'GA', 'flag' => 'Gabon.png'),
            array('name'   => 'Gambia',
                  'name_1' => 'Gambia',
                  'name_2' => 'Gâmbia',
                  'code'   => 'GM',
                  'flag'   => 'Gambia.png'
            ),
            array('name'   => 'Georgia',
                  'name_1' => 'Georgia',
                  'name_2' => 'Geórgia',
                  'code'   => 'GE',
                  'flag'   => 'Georgia.png'
            ),
            array('name' => 'Ghana', 'name_1' => 'Ghana', 'name_2' => 'Gana', 'code' => 'GH', 'flag' => 'Ghana.png'),
            array('name'   => 'Gibraltar',
                  'name_1' => 'Gibraltar',
                  'name_2' => 'Gibraltar',
                  'code'   => 'GI',
                  'flag'   => 'Gibraltar.png'
            ),
            array('name'   => 'Granada',
                  'name_1' => 'Grenada',
                  'name_2' => 'Granada',
                  'code'   => 'GD',
                  'flag'   => 'Grenada.png'
            ),
            array('name'   => 'Grecia',
                  'name_1' => 'Greece',
                  'name_2' => 'Grécia',
                  'code'   => 'GR',
                  'flag'   => 'Greece.png'
            ),
            array('name'   => 'Groenlandia',
                  'name_1' => 'Greenland',
                  'name_2' => 'Groenlândia',
                  'code'   => 'GL',
                  'flag'   => 'Greenland.png'
            ),
            array('name'   => 'Guadalupe',
                  'name_1' => 'Guadeloupe',
                  'name_2' => 'Guadalupe',
                  'code'   => 'GP',
                  'flag'   => 'Guadeloupe.png'
            ),
            array('name' => 'Guam', 'name_1' => 'Guam', 'name_2' => 'Guam', 'code' => 'GU', 'flag' => 'Guam.png'),
            array('name'   => 'Guatemala',
                  'name_1' => 'Guatemala',
                  'name_2' => 'Guatemala',
                  'code'   => 'GT',
                  'flag'   => 'Guatemala.png'
            ),
            array('name'   => 'Guayana Francesa',
                  'name_1' => 'French Guiana',
                  'name_2' => 'Guiana Francesa',
                  'code'   => 'GF',
                  'flag'   => 'Guinea-Bissau.png'
            ),
            array('name'   => 'Guernesey',
                  'name_1' => 'Guernsey',
                  'name_2' => 'Guernsey',
                  'code'   => 'GG',
                  'flag'   => 'Guernsey.png'
            ),
            array('name'   => 'Guinea',
                  'name_1' => 'Guinea',
                  'name_2' => 'Guiné',
                  'code'   => 'GN',
                  'flag'   => 'Guinea.png'
            ),
            array('name'   => 'Guinea Ecuatorial',
                  'name_1' => 'Equatorial Guinea',
                  'name_2' => 'Guiné Equatorial',
                  'code'   => 'GQ',
                  'flag'   => 'Equatorial Guinea.png'
            ),
            array('name'   => 'Guinea-Bisáu',
                  'name_1' => 'Guinea-Bissau',
                  'name_2' => 'Guiné Bissau',
                  'code'   => 'GW',
                  'flag'   => 'Guinea-Bissau.png'
            ),
            array('name'   => 'Guyana',
                  'name_1' => 'Guyana',
                  'name_2' => 'Guiana',
                  'code'   => 'GY',
                  'flag'   => 'Guyana.png'
            ),
            array('name' => 'Haití', 'name_1' => 'Haiti', 'name_2' => 'Haiti', 'code' => 'HT', 'flag' => 'Haiti.png'),
            array('name'   => 'Honduras',
                  'name_1' => 'Honduras',
                  'name_2' => 'Honduras',
                  'code'   => 'HN',
                  'flag'   => 'Honduras.png'
            ),
            array('name'   => 'Hungría',
                  'name_1' => 'Hungary',
                  'name_2' => 'Hungria',
                  'code'   => 'HU',
                  'flag'   => 'Hungary.png'
            ),
            array('name' => 'India', 'name_1' => 'India', 'name_2' => 'Índia', 'code' => 'IN', 'flag' => 'India.png'),
            array('name'   => 'Indonesia',
                  'name_1' => 'Indonesia',
                  'name_2' => 'Indonésia',
                  'code'   => 'ID',
                  'flag'   => 'Indonezia.png'
            ),
            array('name' => 'Irán', 'name_1' => 'Iran', 'name_2' => 'Irã', 'code' => 'IR', 'flag' => 'Iran.png'),
            array('name' => 'Iraq', 'name_1' => 'Iraq', 'name_2' => 'Iraque', 'code' => 'IQ', 'flag' => 'Iraq.png'),
            array('name'   => 'Irlanda',
                  'name_1' => 'Ireland',
                  'name_2' => 'Irlanda',
                  'code'   => 'IE',
                  'flag'   => 'Ireland.png'
            ),
            array('name'   => 'Isla Christmas',
                  'name_1' => 'Christmas Island',
                  'name_2' => 'Ilha Christmas',
                  'code'   => 'CX',
                  'flag'   => null
            ),
            array('name'   => 'Isla de la Ascensión',
                  'name_1' => 'Ascension Island',
                  'name_2' => 'Ilha de Ascensão',
                  'code'   => 'AC',
                  'flag'   => null
            ),
            array('name'   => 'Isla de Man',
                  'name_1' => 'Isle of Man',
                  'name_2' => 'Ilha de Man',
                  'code'   => 'IM',
                  'flag'   => 'Isle of Man.png'
            ),
            array('name' => 'Isla Niue', 'name_1' => 'Niue', 'name_2' => 'Niue', 'code' => 'NU', 'flag' => null),
            array('name'   => 'Isla Norfolk',
                  'name_1' => 'Norfolk Island',
                  'name_2' => 'Ilha Norfolk',
                  'code'   => 'NF',
                  'flag'   => null
            ),
            array('name'   => 'Islandia',
                  'name_1' => 'Iceland',
                  'name_2' => 'Islândia',
                  'code'   => 'IS',
                  'flag'   => 'Iceland.png'
            ),
            array('name'   => 'Islas Åland',
                  'name_1' => 'Åland Islands',
                  'name_2' => 'Ilhas Åland',
                  'code'   => 'AX',
                  'flag'   => null
            ),
            array('name'   => 'Islas Caimán',
                  'name_1' => 'Cayman Islands',
                  'name_2' => 'Ilhas Caiman',
                  'code'   => 'KY',
                  'flag'   => null
            ),
            array('name'   => 'islas Canarias',
                  'name_1' => 'Canary Islands',
                  'name_2' => 'Ilhas Canárias',
                  'code'   => 'IC',
                  'flag'   => null
            ),
            array('name'   => 'Islas Cocos',
                  'name_1' => 'Cocos (Keeling) Islands',
                  'name_2' => 'Ilhas Cocos (Keeling)',
                  'code'   => 'CC',
                  'flag'   => null
            ),
            array('name'   => 'Islas Cook',
                  'name_1' => 'Cook Islands',
                  'name_2' => 'Ilhas Cook',
                  'code'   => 'CK',
                  'flag'   => null
            ),
            array('name'   => 'Islas Feroe',
                  'name_1' => 'Faroe Islands',
                  'name_2' => 'Ilhas Faroe',
                  'code'   => 'FO',
                  'flag'   => null
            ),
            array('name'   => 'Islas Georgia del Sur y Sandwich del Sur',
                  'name_1' => 'South Georgia & South Sandwich Islands',
                  'name_2' => 'Geórgia do Sul e Ilhas Sandwich do Sul',
                  'code'   => 'GS',
                  'flag'   => null
            ),
            array('name'   => 'Islas Malvinas',
                  'name_1' => 'Falkland Islands',
                  'name_2' => 'Ilhas Malvinas',
                  'code'   => 'FK',
                  'flag'   => null
            ),
            array('name'   => 'Islas Marianas del Norte',
                  'name_1' => 'Northern Mariana Islands',
                  'name_2' => 'Ilhas Marianas do Norte',
                  'code'   => 'MP',
                  'flag'   => null
            ),
            array('name'   => 'Islas Marshall',
                  'name_1' => 'Marshall Islands',
                  'name_2' => 'Ilhas Marshall',
                  'code'   => 'MH',
                  'flag'   => null
            ),
            array('name'   => 'Islas menores alejadas de EE. UU.',
                  'name_1' => 'U.S. Outlying Islands',
                  'name_2' => 'Ilhas Distantes dos EUA',
                  'code'   => 'UM',
                  'flag'   => null
            ),
            array('name'   => 'Islas Pitcairn',
                  'name_1' => 'Pitcairn Islands',
                  'name_2' => 'Ilhas Pitcairn',
                  'code'   => 'PN',
                  'flag'   => null
            ),
            array('name'   => 'Islas Salomón',
                  'name_1' => 'Solomon Islands',
                  'name_2' => 'Ilhas Salomão',
                  'code'   => 'SB',
                  'flag'   => null
            ),
            array('name'   => 'Islas Turcas y Caicos',
                  'name_1' => 'Turks & Caicos Islands',
                  'name_2' => 'Ilhas Turks e Caicos',
                  'code'   => 'TC',
                  'flag'   => null
            ),
            array('name'   => 'Islas Vírgenes Británicas',
                  'name_1' => 'British Virgin Islands',
                  'name_2' => 'Ilhas Virgens Britânicas',
                  'code'   => 'VG',
                  'flag'   => null
            ),
            array('name'   => 'Islas Vírgenes de EE. UU.',
                  'name_1' => 'U.S. Virgin Islands',
                  'name_2' => 'Ilhas Virgens dos EUA',
                  'code'   => 'VI',
                  'flag'   => null
            ),
            array('name'   => 'Israel',
                  'name_1' => 'Israel',
                  'name_2' => 'Israel',
                  'code'   => 'IL',
                  'flag'   => 'Israel.png'
            ),
            array('name' => 'Italia', 'name_1' => 'Italy', 'name_2' => 'Itália', 'code' => 'IT', 'flag' => 'Italy.png'),
            array('name'   => 'Jamaica',
                  'name_1' => 'Jamaica',
                  'name_2' => 'Jamaica',
                  'code'   => 'JM',
                  'flag'   => 'Jamaica.png'
            ),
            array('name' => 'Japón', 'name_1' => 'Japan', 'name_2' => 'Japão', 'code' => 'JP', 'flag' => 'Japan.png'),
            array('name'   => 'Jersey',
                  'name_1' => 'Jersey',
                  'name_2' => 'Jersey',
                  'code'   => 'JE',
                  'flag'   => 'Jersey.png'
            ),
            array('name'   => 'Jordania',
                  'name_1' => 'Jordan',
                  'name_2' => 'Jordânia',
                  'code'   => 'JO',
                  'flag'   => 'Jordan.png'
            ),
            array('name'   => 'Kazajistán',
                  'name_1' => 'Kazakhstan',
                  'name_2' => 'Cazaquistão',
                  'code'   => 'KZ',
                  'flag'   => 'Kazakhstan.png'
            ),
            array('name' => 'Kenia', 'name_1' => 'Kenya', 'name_2' => 'Quênia', 'code' => 'KE', 'flag' => 'Kenya.png'),
            array('name'   => 'Kirguistán',
                  'name_1' => 'Kyrgyzstan',
                  'name_2' => 'Quirguistão',
                  'code'   => 'KG',
                  'flag'   => 'Kyrgyzstan.png'
            ),
            array('name'   => 'Kiribati',
                  'name_1' => 'Kiribati',
                  'name_2' => 'Quiribati',
                  'code'   => 'KI',
                  'flag'   => 'Kiribati.png'
            ),
            array('name' => 'Kosovo', 'name_1' => 'Kosovo', 'name_2' => 'Kosovo', 'code' => 'XK', 'flag' => null),
            array('name'   => 'Kuwait',
                  'name_1' => 'Kuwait',
                  'name_2' => 'Kuwait',
                  'code'   => 'KW',
                  'flag'   => 'Kuwait.png'
            ),
            array('name' => 'Laos', 'name_1' => 'Laos', 'name_2' => 'Laos', 'code' => 'LA', 'flag' => 'Laos.png'),
            array('name'   => 'Lesoto',
                  'name_1' => 'Lesotho',
                  'name_2' => 'Lesoto',
                  'code'   => 'LS',
                  'flag'   => 'Lesotho.png'
            ),
            array('name'   => 'Letonia',
                  'name_1' => 'Latvia',
                  'name_2' => 'Letônia',
                  'code'   => 'LV',
                  'flag'   => 'Latvia.png'
            ),
            array('name'   => 'Líbano',
                  'name_1' => 'Lebanon',
                  'name_2' => 'Líbano',
                  'code'   => 'LB',
                  'flag'   => 'Lebanon.png'
            ),
            array('name'   => 'Liberia',
                  'name_1' => 'Liberia',
                  'name_2' => 'Libéria',
                  'code'   => 'LR',
                  'flag'   => 'Liberia.png'
            ),
            array('name' => 'Libia', 'name_1' => 'Libya', 'name_2' => 'Líbia', 'code' => 'LY', 'flag' => 'Libya.png'),
            array('name'   => 'Liechtenstein',
                  'name_1' => 'Liechtenstein',
                  'name_2' => 'Liechtenstein',
                  'code'   => 'LI',
                  'flag'   => 'Liechtenshein.png'
            ),
            array('name'   => 'Lituania',
                  'name_1' => 'Lithuania',
                  'name_2' => 'Lituânia',
                  'code'   => 'LT',
                  'flag'   => 'Lithuania.png'
            ),
            array('name'   => 'Luxemburgo',
                  'name_1' => 'Luxembourg',
                  'name_2' => 'Luxemburgo',
                  'code'   => 'LU',
                  'flag'   => 'Luxembourg.png'
            ),
            array('name'   => 'Macedonia',
                  'name_1' => 'Macedonia',
                  'name_2' => 'Macedônia',
                  'code'   => 'MK',
                  'flag'   => 'Macedonia.png'
            ),
            array('name'   => 'Madagascar',
                  'name_1' => 'Madagascar',
                  'name_2' => 'Madagascar',
                  'code'   => 'MG',
                  'flag'   => 'Madagascar.png'
            ),
            array('name'   => 'Malasia',
                  'name_1' => 'Malaysia',
                  'name_2' => 'Malásia',
                  'code'   => 'MY',
                  'flag'   => 'Malaysia.png'
            ),
            array('name'   => 'Malaui',
                  'name_1' => 'Malawi',
                  'name_2' => 'Malawi',
                  'code'   => 'MW',
                  'flag'   => 'Malawi.png'
            ),
            array('name' => 'Maldivas', 'name_1' => 'Maldives', 'name_2' => 'Maldivas', 'code' => 'MV', 'flag' => null),
            array('name' => 'Mali', 'name_1' => 'Mali', 'name_2' => 'Mali', 'code' => 'ML', 'flag' => 'Mali.png'),
            array('name' => 'Malta', 'name_1' => 'Malta', 'name_2' => 'Malta', 'code' => 'MT', 'flag' => 'Malta.png'),
            array('name'   => 'Marruecos',
                  'name_1' => 'Morocco',
                  'name_2' => 'Marrocos',
                  'code'   => 'MA',
                  'flag'   => 'Morocco.png'
            ),
            array('name'   => 'Martinica',
                  'name_1' => 'Martinique',
                  'name_2' => 'Martinica',
                  'code'   => 'MQ',
                  'flag'   => 'Martinique.png'
            ),
            array('name'   => 'Mauricio',
                  'name_1' => 'Mauritius',
                  'name_2' => 'Maurício',
                  'code'   => 'MU',
                  'flag'   => 'Mauritius.png'
            ),
            array('name'   => 'Mauritania',
                  'name_1' => 'Mauritania',
                  'name_2' => 'Mauritânia',
                  'code'   => 'MR',
                  'flag'   => 'Mauritania.png'
            ),
            array('name' => 'Mayotte', 'name_1' => 'Mayotte', 'name_2' => 'Mayotte', 'code' => 'YT', 'flag' => null),
            array('name'   => 'México',
                  'name_1' => 'Mexico',
                  'name_2' => 'México',
                  'code'   => 'MX',
                  'flag'   => 'Mexico.png'
            ),
            array('name'   => 'Micronesia',
                  'name_1' => 'Micronesia',
                  'name_2' => 'Micronésia',
                  'code'   => 'FM',
                  'flag'   => 'Micronesia.png'
            ),
            array('name'   => 'Moldavia',
                  'name_1' => 'Moldova',
                  'name_2' => 'Moldávia',
                  'code'   => 'MD',
                  'flag'   => 'Moldova.png'
            ),
            array('name'   => 'Mónaco',
                  'name_1' => 'Monaco',
                  'name_2' => 'Mônaco',
                  'code'   => 'MC',
                  'flag'   => 'Monaco.png'
            ),
            array('name'   => 'Mongolia',
                  'name_1' => 'Mongolia',
                  'name_2' => 'Mongólia',
                  'code'   => 'MN',
                  'flag'   => 'Mongolia.png'
            ),
            array('name'   => 'Montenegro',
                  'name_1' => 'Montenegro',
                  'name_2' => 'Montenegro',
                  'code'   => 'ME',
                  'flag'   => null
            ),
            array('name'   => 'Montserrat',
                  'name_1' => 'Montserrat',
                  'name_2' => 'Montserrat',
                  'code'   => 'MS',
                  'flag'   => 'Montserrat.png'
            ),
            array('name'   => 'Mozambique',
                  'name_1' => 'Mozambique',
                  'name_2' => 'Moçambique',
                  'code'   => 'MZ',
                  'flag'   => 'Mozambique.png'
            ),
            array('name'   => 'Myanmar (Birmania)',
                  'name_1' => 'Myanmar (Burma)',
                  'name_2' => 'Mianmar (Birmânia)',
                  'code'   => 'MM',
                  'flag'   => 'Myanmar(Burma).png'
            ),
            array('name'   => 'Namibia',
                  'name_1' => 'Namibia',
                  'name_2' => 'Namíbia',
                  'code'   => 'NA',
                  'flag'   => 'Namibia.png'
            ),
            array('name' => 'Nauru', 'name_1' => 'Nauru', 'name_2' => 'Nauru', 'code' => 'NR', 'flag' => 'Nauru.png'),
            array('name' => 'Nepal', 'name_1' => 'Nepal', 'name_2' => 'Nepal', 'code' => 'NP', 'flag' => 'Nepal.png'),
            array('name'   => 'Nicaragua',
                  'name_1' => 'Nicaragua',
                  'name_2' => 'Nicarágua',
                  'code'   => 'NI',
                  'flag'   => 'Nicaragua.png'
            ),
            array('name' => 'Níger', 'name_1' => 'Niger', 'name_2' => 'Níger', 'code' => 'NE', 'flag' => 'Niger.png'),
            array('name'   => 'Nigeria',
                  'name_1' => 'Nigeria',
                  'name_2' => 'Nigéria',
                  'code'   => 'NG',
                  'flag'   => 'Nigeria.png'
            ),
            array('name'   => 'Noruega',
                  'name_1' => 'Norway',
                  'name_2' => 'Noruega',
                  'code'   => 'NO',
                  'flag'   => 'Norway.png'
            ),
            array('name'   => 'Nueva Caledonia',
                  'name_1' => 'New Caledonia',
                  'name_2' => 'Nova Caledônia',
                  'code'   => 'NC',
                  'flag'   => null
            ),
            array('name'   => 'Nueva Zelanda',
                  'name_1' => 'New Zealand',
                  'name_2' => 'Nova Zelândia',
                  'code'   => 'NZ',
                  'flag'   => 'New Zealand.png'
            ),
            array('name' => 'Omán', 'name_1' => 'Oman', 'name_2' => 'Omã', 'code' => 'OM', 'flag' => 'Oman.png'),
            array('name'   => 'Países Bajos',
                  'name_1' => 'Netherlands',
                  'name_2' => 'Holanda',
                  'code'   => 'NL',
                  'flag'   => 'Netherlands.png'
            ),
            array('name'   => 'Pakistán',
                  'name_1' => 'Pakistan',
                  'name_2' => 'Paquistão',
                  'code'   => 'PK',
                  'flag'   => 'Pakistan.png'
            ),
            array('name' => 'Palau', 'name_1' => 'Palau', 'name_2' => 'Palau', 'code' => 'PW', 'flag' => null),
            array('name'   => 'Panamá',
                  'name_1' => 'Panama',
                  'name_2' => 'Panamá',
                  'code'   => 'PA',
                  'flag'   => 'Panama.png'
            ),
            array('name'   => 'Papúa Nueva Guinea',
                  'name_1' => 'Papua New Guinea',
                  'name_2' => 'Papua-Nova Guiné',
                  'code'   => 'PG',
                  'flag'   => 'Papua New Guinea.png'
            ),
            array('name'   => 'Paraguay',
                  'name_1' => 'Paraguay',
                  'name_2' => 'Paraguai',
                  'code'   => 'PY',
                  'flag'   => 'Paraguay.png'
            ),
            array('name' => 'Perú', 'name_1' => 'Peru', 'name_2' => 'Peru', 'code' => 'PE', 'flag' => 'Peru.png'),
            array('name'   => 'Polinesia Francesa',
                  'name_1' => 'French Polynesia',
                  'name_2' => 'Polinésia Francesa',
                  'code'   => 'PF',
                  'flag'   => null
            ),
            array('name'   => 'Polonia',
                  'name_1' => 'Poland',
                  'name_2' => 'Polônia',
                  'code'   => 'PL',
                  'flag'   => 'Poland.png'
            ),
            array('name'   => 'Portugal',
                  'name_1' => 'Portugal',
                  'name_2' => 'Portugal',
                  'code'   => 'PT',
                  'flag'   => 'Portugal.png'
            ),
            array('name'   => 'Puerto Rico',
                  'name_1' => 'Puerto Rico',
                  'name_2' => 'Porto Rico',
                  'code'   => 'PR',
                  'flag'   => 'Puerto Rico.png'
            ),
            array('name'   => 'RAE de Hong Kong (China)',
                  'name_1' => 'Hong Kong SAR China',
                  'name_2' => 'Hong Kong, RAE da China',
                  'code'   => 'HK',
                  'flag'   => 'Hong Kong.png'
            ),
            array('name'   => 'RAE de Macao (China)',
                  'name_1' => 'Macau SAR China',
                  'name_2' => 'Macau, RAE da China',
                  'code'   => 'MO',
                  'flag'   => 'Macao.png'
            ),
            array('name'   => 'Reino Unido',
                  'name_1' => 'United Kingdom',
                  'name_2' => 'Reino Unido',
                  'code'   => 'GB',
                  'flag'   => 'United Kingdom(Great Britain).png'
            ),
            array('name'   => 'República Centroafricana',
                  'name_1' => 'Central African Republic',
                  'name_2' => 'República Centro-Africana',
                  'code'   => 'CF',
                  'flag'   => 'Central African Republic.png'
            ),
            array('name'   => 'República Checa',
                  'name_1' => 'Czech Republic',
                  'name_2' => 'República Tcheca',
                  'code'   => 'CZ',
                  'flag'   => 'Czech Republic.png'
            ),
            array('name'   => 'República del Congo',
                  'name_1' => 'Congo - Brazzaville',
                  'name_2' => 'Congo - Brazzaville',
                  'code'   => 'CG',
                  'flag'   => 'Congo-Brazzaville.png'
            ),
            array('name'   => 'República Democrática del Congo',
                  'name_1' => 'Congo - Kinshasa',
                  'name_2' => 'Congo - Kinshasa',
                  'code'   => 'CD',
                  'flag'   => 'Congo-Kinshasa(Zaire).png'
            ),
            array('name'   => 'República Dominicana',
                  'name_1' => 'Dominican Republic',
                  'name_2' => 'República Dominicana',
                  'code'   => 'DO',
                  'flag'   => 'Dominican Republic.png'
            ),
            array('name'   => 'Reunión',
                  'name_1' => 'Réunion',
                  'name_2' => 'Reunião',
                  'code'   => 'RE',
                  'flag'   => 'Reunion.png'
            ),
            array('name'   => 'Ruanda',
                  'name_1' => 'Rwanda',
                  'name_2' => 'Ruanda',
                  'code'   => 'RW',
                  'flag'   => 'Rwanda.png'
            ),
            array('name'   => 'Rumanía',
                  'name_1' => 'Romania',
                  'name_2' => 'Romênia',
                  'code'   => 'RO',
                  'flag'   => 'Romania.png'
            ),
            array('name'   => 'Rusia',
                  'name_1' => 'Russia',
                  'name_2' => 'Rússia',
                  'code'   => 'RU',
                  'flag'   => 'Russian Federation.png'
            ),
            array('name'   => 'Sahara Occidental',
                  'name_1' => 'Western Sahara',
                  'name_2' => 'Saara Ocidental',
                  'code'   => 'EH',
                  'flag'   => 'Western Sahara.png'
            ),
            array('name' => 'Samoa', 'name_1' => 'Samoa', 'name_2' => 'Samoa', 'code' => 'WS', 'flag' => 'Samoa.png'),
            array('name'   => 'Samoa Americana',
                  'name_1' => 'American Samoa',
                  'name_2' => 'Samoa Americana',
                  'code'   => 'AS',
                  'flag'   => null
            ),
            array('name'   => 'San Bartolomé',
                  'name_1' => 'St. Barthélemy',
                  'name_2' => 'São Bartolomeu',
                  'code'   => 'BL',
                  'flag'   => null
            ),
            array('name'   => 'San Cristóbal y Nieves',
                  'name_1' => 'St. Kitts & Nevis',
                  'name_2' => 'São Cristóvão e Nevis',
                  'code'   => 'KN',
                  'flag'   => null
            ),
            array('name'   => 'San Marino',
                  'name_1' => 'San Marino',
                  'name_2' => 'San Marino',
                  'code'   => 'SM',
                  'flag'   => 'San Marino.png'
            ),
            array('name'   => 'San Martín',
                  'name_1' => 'St. Martin',
                  'name_2' => 'São Martinho',
                  'code'   => 'MF',
                  'flag'   => null
            ),
            array('name'   => 'San Pedro y Miquelón',
                  'name_1' => 'St. Pierre & Miquelon',
                  'name_2' => 'Saint Pierre e Miquelon',
                  'code'   => 'PM',
                  'flag'   => null
            ),
            array('name'   => 'San Vicente y las Granadinas',
                  'name_1' => 'St. Vincent & Grenadines',
                  'name_2' => 'São Vicente e Granadinas',
                  'code'   => 'VC',
                  'flag'   => 'St Vincent & the Grenadines.png'
            ),
            array('name'   => 'Santa Elena',
                  'name_1' => 'St. Helena',
                  'name_2' => 'Santa Helena',
                  'code'   => 'SH',
                  'flag'   => null
            ),
            array('name'   => 'Santa Lucía',
                  'name_1' => 'St. Lucia',
                  'name_2' => 'Santa Lúcia',
                  'code'   => 'LC',
                  'flag'   => 'Saint Lucia.png'
            ),
            array('name'   => 'Santo Tomé y Príncipe',
                  'name_1' => 'São Tomé & Príncipe',
                  'name_2' => 'São Tomé e Príncipe',
                  'code'   => 'ST',
                  'flag'   => null
            ),
            array('name'   => 'Senegal',
                  'name_1' => 'Senegal',
                  'name_2' => 'Senegal',
                  'code'   => 'SN',
                  'flag'   => 'Senegal.png'
            ),
            array('name' => 'Serbia', 'name_1' => 'Serbia', 'name_2' => 'Sérvia', 'code' => 'RS', 'flag' => null),
            array('name'   => 'Seychelles',
                  'name_1' => 'Seychelles',
                  'name_2' => 'Seychelles',
                  'code'   => 'SC',
                  'flag'   => 'Seychelles.png'
            ),
            array('name'   => 'Sierra Leona',
                  'name_1' => 'Sierra Leone',
                  'name_2' => 'Serra Leoa',
                  'code'   => 'SL',
                  'flag'   => 'Sierra Leone.png'
            ),
            array('name'   => 'Singapur',
                  'name_1' => 'Singapore',
                  'name_2' => 'Cingapura',
                  'code'   => 'SG',
                  'flag'   => 'Singapore.png'
            ),
            array('name'   => 'Sint Maarten',
                  'name_1' => 'Sint Maarten',
                  'name_2' => 'Sint Maarten',
                  'code'   => 'SX',
                  'flag'   => null
            ),
            array('name' => 'Siria', 'name_1' => 'Syria', 'name_2' => 'Síria', 'code' => 'SY', 'flag' => 'Syria.png'),
            array('name'   => 'Somalia',
                  'name_1' => 'Somalia',
                  'name_2' => 'Somália',
                  'code'   => 'SO',
                  'flag'   => 'Somalia.png'
            ),
            array('name'   => 'Sri Lanka',
                  'name_1' => 'Sri Lanka',
                  'name_2' => 'Sri Lanka',
                  'code'   => 'LK',
                  'flag'   => 'Sri Lanka.png'
            ),
            array('name'   => 'Suazilandia',
                  'name_1' => 'Swaziland',
                  'name_2' => 'Suazilândia',
                  'code'   => 'SZ',
                  'flag'   => 'Swaziland.png'
            ),
            array('name'   => 'Sudáfrica',
                  'name_1' => 'South Africa',
                  'name_2' => 'África do Sul',
                  'code'   => 'ZA',
                  'flag'   => 'South Africa.png'
            ),
            array('name' => 'Sudán', 'name_1' => 'Sudan', 'name_2' => 'Sudão', 'code' => 'SD', 'flag' => 'Sudan.png'),
            array('name'   => 'Sudán del Sur',
                  'name_1' => 'South Sudan',
                  'name_2' => 'Sudão do Sul',
                  'code'   => 'SS',
                  'flag'   => null
            ),
            array('name'   => 'Suecia',
                  'name_1' => 'Sweden',
                  'name_2' => 'Suécia',
                  'code'   => 'SE',
                  'flag'   => 'Sweden.png'
            ),
            array('name'   => 'Suiza',
                  'name_1' => 'Switzerland',
                  'name_2' => 'Suíça',
                  'code'   => 'CH',
                  'flag'   => 'Switzerland.png'
            ),
            array('name'   => 'Surinam',
                  'name_1' => 'Suriname',
                  'name_2' => 'Suriname',
                  'code'   => 'SR',
                  'flag'   => 'Suriname.png'
            ),
            array('name'   => 'Svalbard y Jan Mayen',
                  'name_1' => 'Svalbard & Jan Mayen',
                  'name_2' => 'Svalbard e Jan Mayen',
                  'code'   => 'SJ',
                  'flag'   => null
            ),
            array('name'   => 'Tailandia',
                  'name_1' => 'Thailand',
                  'name_2' => 'Tailândia',
                  'code'   => 'TH',
                  'flag'   => 'Thailand.png'
            ),
            array('name'   => 'Taiwán',
                  'name_1' => 'Taiwan',
                  'name_2' => 'Taiwan',
                  'code'   => 'TW',
                  'flag'   => 'Taiwan.png'
            ),
            array('name'   => 'Tanzania',
                  'name_1' => 'Tanzania',
                  'name_2' => 'Tanzânia',
                  'code'   => 'TZ',
                  'flag'   => 'Tanzania.png'
            ),
            array('name'   => 'Tayikistán',
                  'name_1' => 'Tajikistan',
                  'name_2' => 'Tajiquistão',
                  'code'   => 'TJ',
                  'flag'   => 'Tajikistan.png'
            ),
            array('name'   => 'Territorio Británico del Océano Índico',
                  'name_1' => 'British Indian Ocean Territory',
                  'name_2' => 'Território Britânico do Oceano Índico',
                  'code'   => 'IO',
                  'flag'   => null
            ),
            array('name'   => 'Territorios Australes Franceses',
                  'name_1' => 'French Southern Territories',
                  'name_2' => 'Territórios Franceses do Sul',
                  'code'   => 'TF',
                  'flag'   => null
            ),
            array('name'   => 'Territorios Palestinos',
                  'name_1' => 'Palestinian Territories',
                  'name_2' => 'Territórios palestinos',
                  'code'   => 'PS',
                  'flag'   => 'Palestine.png'
            ),
            array('name'   => 'Timor Oriental',
                  'name_1' => 'Timor-Leste',
                  'name_2' => 'Timor-Leste',
                  'code'   => 'TL',
                  'flag'   => 'Timor-Leste.png.png'
            ),
            array('name' => 'Togo', 'name_1' => 'Togo', 'name_2' => 'Togo', 'code' => 'TG', 'flag' => 'Togo.png'),
            array('name' => 'Tokelau', 'name_1' => 'Tokelau', 'name_2' => 'Tokelau', 'code' => 'TK', 'flag' => null),
            array('name' => 'Tonga', 'name_1' => 'Tonga', 'name_2' => 'Tonga', 'code' => 'TO', 'flag' => 'Tonga.png'),
            array('name'   => 'Trinidad y Tobago',
                  'name_1' => 'Trinidad & Tobago',
                  'name_2' => 'Trinidad e Tobago',
                  'code'   => 'TT',
                  'flag'   => 'Trinidad & Tobago.png'
            ),
            array('name'   => 'Tristán da Cunha',
                  'name_1' => 'Tristan da Cunha',
                  'name_2' => 'Tristão da Cunha',
                  'code'   => 'TA',
                  'flag'   => null
            ),
            array('name'   => 'Túnez',
                  'name_1' => 'Tunisia',
                  'name_2' => 'Tunísia',
                  'code'   => 'TN',
                  'flag'   => 'Tunisia.png'
            ),
            array('name'   => 'Turkmenistán',
                  'name_1' => 'Turkmenistan',
                  'name_2' => 'Turcomenistão',
                  'code'   => 'TM',
                  'flag'   => 'Turkmenistan.png'
            ),
            array('name'   => 'Turquía',
                  'name_1' => 'Turkey',
                  'name_2' => 'Turquia',
                  'code'   => 'TR',
                  'flag'   => 'Turkey.png'
            ),
            array('name'   => 'Tuvalu',
                  'name_1' => 'Tuvalu',
                  'name_2' => 'Tuvalu',
                  'code'   => 'TV',
                  'flag'   => 'Tuvalu.png'
            ),
            array('name'   => 'Ucrania',
                  'name_1' => 'Ukraine',
                  'name_2' => 'Ucrânia',
                  'code'   => 'UA',
                  'flag'   => 'Ukraine.png'
            ),
            array('name'   => 'Uganda',
                  'name_1' => 'Uganda',
                  'name_2' => 'Uganda',
                  'code'   => 'UG',
                  'flag'   => 'Uganda.png'
            ),
            array('name'   => 'Uruguay',
                  'name_1' => 'Uruguay',
                  'name_2' => 'Uruguai',
                  'code'   => 'UY',
                  'flag'   => 'Uruguay.png'
            ),
            array('name'   => 'Uzbekistán',
                  'name_1' => 'Uzbekistan',
                  'name_2' => 'Uzbequistão',
                  'code'   => 'UZ',
                  'flag'   => 'Uzbekistan.png'
            ),
            array('name'   => 'Vanuatu',
                  'name_1' => 'Vanuatu',
                  'name_2' => 'Vanuatu',
                  'code'   => 'VU',
                  'flag'   => 'Vanutau.png'
            ),
            array('name'   => 'Venezuela',
                  'name_1' => 'Venezuela',
                  'name_2' => 'Venezuela',
                  'code'   => 'VE',
                  'flag'   => 'Venezuela.png'
            ),
            array('name'   => 'Vietnam',
                  'name_1' => 'Vietnam',
                  'name_2' => 'Vietnã',
                  'code'   => 'VN',
                  'flag'   => 'Viet Nam.png'
            ),
            array('name'   => 'Wallis y Futuna',
                  'name_1' => 'Wallis & Futuna',
                  'name_2' => 'Wallis e Futuna',
                  'code'   => 'WF',
                  'flag'   => null
            ),
            array('name' => 'Yemen', 'name_1' => 'Yemen', 'name_2' => 'Iêmen', 'code' => 'YE', 'flag' => 'Yemen.png'),
            array('name' => 'Yibuti', 'name_1' => 'Djibouti', 'name_2' => 'Djibuti', 'code' => 'DJ', 'flag' => null),
            array('name'   => 'Zambia',
                  'name_1' => 'Zambia',
                  'name_2' => 'Zâmbia',
                  'code'   => 'ZM',
                  'flag'   => 'Zambia.png'
            ),
            array('name'   => 'Zimbabue',
                  'name_1' => 'Zimbabwe',
                  'name_2' => 'Zimbábue',
                  'code'   => 'ZW',
                  'flag'   => 'Zimbabwe.png'
            )
        );

        foreach ($countries as $country) {
            Country::create([
                'country_name' => $country['name_1'],
                'country_code' => $country['code']
            ]);
        }
    }
}
